### ISSUE TITLE
Adding sbs chanting book

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/tpr_downloads#5]
Bhante,

Is it possible to add the "SBS Pali-English recitation book" to the TPR extensions?

Original repo of SBS book:

https://github.com/sasanarakkha/pali-english-recitations

Latest update of SBS book, exported in various formats:

https://github.com/sasanarakkha/pali-english-recitations/releases/latest

_Originally posted by @Devamitta in https://github.com/bksubhuti/tipitaka-pali-reader/discussions/250_

**Comment by bksubhuti** [comment]
You can look around this repo.
You can copy the format.  You will need to ask a programmer of any language to make this work.

You can look at this directory here.
https://github.com/bksubhuti/tpr_downloads/tree/master/release_zips

I don't have a doc on how to make this, but it is not so difficult if you have someone technical make it.
You might even succeed with chatgpt but you still need a little knowledge in programming to do it.

**Comment by bksubhuti** [comment]
Once you have the sql file, you should try to import the sql directly into the sqlite database browser.  

You can do this with the desktop TPR edition but not the mobile edition.
You will need to globally search for sqlite files or the tipitaka_pali_reader directory
or the file.. tipitaka_pali.db

desktop browser is here
https://sqlitebrowser.org/

If you are using linux (recommended), then you can install the browser with the ubuntu repos or store or synaptic (best recommended).

My linux TPR installs the db to this directory:
~/.local/share/tipitaka_pali_reader/tipitaka_pali.db

You can find in similar operating systems according to the personal folder structure or ask chatgpt for your OS.

Then.. you just open the db and do file/import/sql  see what happens.
Then close and open the TPR app (small refresh bug) and see if the book is in the annya section of /chanting

Best of luck.
When you get that far, I'll take over and see about adding it to the repo.

Censoring Disclaimer:
If your chanting book has **ebt**, it will not be added so you might want to remove any EBT or references if they are part of the book.  Otherwise, I'll do my best, but I might  be slow.  
Post canonical pāḷi is fine (like what is found most chanting books).

**Comment by Devamitta** [comment]
Our chanting book has a combination of canonical texts and post-canonical texts.

I am interested in adding the whole book, so Pāli students can read it all in one place, rather than searching sutta after sutta.

Is it possible to add the whole book with all Pāli texts included?

**Comment by Devamitta** [comment]
Does Bhante referring to actual word "EBT" ?

Or chanting book does not have this word or similar.

**Comment by bksubhuti** [comment]
EBT means non pali texts that you compare and use to criticize the pali with.  Like most of the talks found in SBS.

**Comment by Devamitta** [comment]
> 
> Best of luck.
> When you get that far, I'll take over and see about adding it to the repo.
> 


Ok Bhante, thanks for detailed instructions.
Will try to follow.

And looking forward to having changing book in TPR. So far this app is the best for reading Pāli texts.

**Comment by bksubhuti** [comment]
We are glad you like TPR.
I think you might define EBT differently than  me.. The chanting book seemed by glance to be free from ebt.
I won't have time to review it .. but can you confirm you don't have ebt as I understand that word?

**Comment by Devamitta** [comment]
We do not have any non-Pāli Buddhist texts in our chanting book.

**Comment by bksubhuti** [comment]
Please read very carefully the footnotes.  I don't have time.  but 
**"Annotated by Ven. Ariyadhammika"** throws up a red flag for his reputation as an EBT teacher and one who seems to criticize the compilers of the pali tipitaka of doctoring the texts and taking mahayana early texts as a higher authority.  

**There should be no footnote references that go against Classical Theravada Philosophy.**  He would definitely know what I'm talking about since he is familiar with me.  You should read yourself and also discuss with him.  Bring to my attention anything you have doubt about whether I will accept it or not.
   
Perhaps it is better not to have the footnotes in an extension.  I find to have the bare minimum much better since I use the IIT book to navigate and jump to sections almost week-daily while I'm leading the chanting.

I also find that the pali in bold is much better.  Stylistically and academically they say it should be italics.. but I think that bold pali and normal text for english works best. 
 
 Furthermore, if the foreign language is a small portion of the book that might play a good role.  I doubt it for chanting books.  Generally, italics are more difficult to read and you want the pali to stick out.
It is your puppy though.  You can do whatever you want for typeface.  
I'm not sure TPR supports italics.  Maybe you can look at other extension books and see if we do.  We might.  I have to check the code.

Ven anandajoti did bold for pali
Ven Nyanatusita originally had italics in his patimokkha book in italic pali until I convinced him not to.
IIT chanting book is pure pali no english.  It is all single normal font.  But when it is in pali/ english in the future.. it would be good to have the pali in bold.

**Comment by Devamitta** [comment]
The easiest solution will be to remove all footnotes. They are not relevant anyway for the purpose of reading Pāli with the help of dictionaries (as I see the main purpose of TPR).

So I will prepare a version with only Pāli chants and English translation.

I can make the Pāli bold and the English normal. I will be back to my laptop by the end of next week and can start to do it then.

**Comment by bksubhuti** [comment]
Sounds like a plan .  I recommend Pali as bold if you have English too .   You can see ven anandajoti's extension. But that is your decision

**Comment by bksubhuti** [comment]
The page size is something I made up.  You can pick any size you want.  In retrospect I think the pages should be 25% smaller.  But it all works .
Why?  The indexing often puts you on the beginning of the "page" so it might not be apparent where the sutta or toc item is when you jump to it.
You can play with the number of lines per page and see and see.  It is your book .  There might be some code samples in the repo.  It is not very clean and organized for the code samples and reproducing older works.

**Comment by Devamitta** [comment]
Bhante, I finally finished making sbs_pali_recitation.sql, I made it in exactly same way as for example iit_chantingbook.sql or Chanting_for_Meditators.sql which I found in `/home/deva/.var/app/org.americanmonk.TipitakaPaliReader/data/tipitaka_pali_reader/`

But I'm having trouble to make db from them, DB Browser give the same error when I am importing any of those 3 sql files:
![image](https://github.com/user-attachments/assets/382ab32f-3070-41cb-b0cf-d039c007e4f2)

Here is a sbs_pali_recitation.sql file which I created:
https://drive.google.com/file/d/12ai21A6wJByzRxxLpvPDaxYCswq3dl1J/view?usp=sharing

**Comment by bksubhuti** [comment]
It works fine.. but you just probably didn't have the database open to do that.
You need to open the tpr db.
This was the result
Execution finished without errors.
Result: query executed successfully. Took 8ms, 0 rows affected
At line 1:
DELETE from tocs where book_id = 'annya_sbs_chants'

**Comment by bksubhuti** [comment]
I imported your file.. It imports.  I think you just need to have the proper db open.  I bet you imported to a new db when it asked you.  Now All you need to do is add line breaks.. either surround your lines with 
`<p>sometext</p>`  
or use 
`<BR> 
`where you want a new line.
You have to learn just a little bit about html.. and all will work fine.  You are almost there.

![image](https://github.com/user-attachments/assets/a72b5d92-5222-4e4a-b63f-50cbefc396bc)

**Comment by Devamitta** [comment]
Thank you, Bhante,

Added `<p> ... </p>`

https://drive.google.com/file/d/12ai21A6wJByzRxxLpvPDaxYCswq3dl1J/view?usp=sharing

**Comment by bksubhuti** [comment]
I had a chance to install the sql file.. Looks like it works well.  
I will try to add it to the list this weekend and it will be live via the extension downloader.
It should not take long to add at this stage.  I appreciate the leg work you did.  It makes my job easier.

**Comment by bksubhuti** [comment]
Added sbs chants and tested.  Congratulations.
It is in the TPR extensions now.
If you have changes, you can send me the file as a zip and I'll drop it in.
Better is to do a PR  (pull request).  This is the  proper way to do it.

**Comment by Devamitta** [comment]
thank you Bhante,

everything working well!
